### ISSUE TITLE
リボンの処遇について

### ISSUE THREAD

**Issue by miramiku** [miramiku/Cypress#17]
カードのデザインにおいて重要な位置をしめる、品質を表すリボン。

リボンを表現に必要な以下のコードが諸悪の根源となってツールボックスが表示できない。

``` css
.equipment-card {
    overflow: hidden;
}
```

リボンの表現を捨てる事は出来ないので共存させるためにリボンを画像化するべきか。
